### ISSUE TITLE
[question] Stringed instruments?

### ISSUE THREAD

**Issue by baskeboler** [ctford/leipzig#16]
Hi there, I am really digging this library but I am having a bit of a hard time using it with stringed instruments.  I tried to write an example based on the overtone stringed synth examples [here](https://github.com/baskeboler/highway-to-hell) but it is not clear to me how I could express the chords in a more elegant way. Any ideas or suggestions?

**Comment by ctford** [comment]
Very cool!

A couple of suggestions on chords. First, `phrase` accepts single pitches
(numbers), tone clusters (vectors) and chords (maps), so you could consider
using that instead of the `rhythm`/`having` combo you've got going.

The downside of that is that it flattens chords into individual notes, so
it may or may not work with your instruments.

For your repeated chords, you could consider using `(mapcat repeat [reps]
[chords])` as an idiom to reduce redundant chord descriptions.

Rock on!

Chris

**Comment by baskeboler** [comment]
Thanks for your reply! After posting my question I realized that using `phrase` is a lot cleaner. My knowledge of guitar is very limited (knowledge of piano is nil :P) but getting guitar tabs from the web is a fun starting point and digging into leipzig has been enlightening. I wrote a little function [here](https://github.com/baskeboler/overtone-guitar-utils/blob/master/src/overtone_guitar_utils/core.clj) to translate the guitar chord vectors into midi chords that I think might be useful and a lot more friendlier to use with leipzig transformations.
